api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  proxy:
    type: docker_logs
    include_containers:
      - arkd-proxy
  task_docker_logs:
    type: docker_logs
    exclude_containers:
      - arkd-proxy
sinks:
  loki_tasks:
    type: loki
    inputs:
      - task_docker_logs
    endpoint: http://localhost:3100
    encoding:
      codec: json
    labels:
      source: vector
      service_name: arkd_worker
      deployment_name: "{{ label.arkd_deployment }}"
      app_name: "{{ label.arkd_app }}"
      stack_name: "{{ label.arkd_stack }}"
      arkd_worker_id: "{{ label.arkd_worker_id }}"

  default_file:
    type: file
    inputs:
      - proxy
      - task_docker_logs
    path: "./tmp/logs/vector-%Y-%m-%d.log"
    encoding:
      codec: json
